#!/bin/bash

[ `uname -s` != "Linux" ] && exit 0

NRNODES=`grep processor /proc/cpuinfo | wc -l`
need=0

for i in `seq 0 $(( $NRNODES - 1 ))`
do
	if [ ! -c /dev/cpu/$i/cpuid ] ; then
		echo "*** No /dev/cpu/$i/cpuid found."
		need=1
	fi

	if [ ! -c /dev/cpu/$i/msr ] ; then
		echo "*** No /dev/cpu/$i/msr found."
		need=1
	fi
done

if test "$need" -eq 1 ; then
	echo "type \"make nodes\" as root to install device nodes"
	echo "You will also need msr driver installed"
fi

